<a href="https://colab.research.google.com/github/uichann/My_Repository/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.random.randn(100)
arr

array([-0.70668647, -2.51107142,  1.04474751, -0.47083928,  0.55401127,
        0.59227922,  0.33437406,  0.3896258 ,  0.70357446,  0.49497148,
       -1.49368127,  0.45847376, -0.68653878,  1.17856371, -0.49823629,
        0.34177858,  0.18011313,  0.78723247, -1.14264539,  1.12064626,
       -0.89584457,  0.42671132,  0.33798877,  0.08986897, -0.14245392,
       -0.25328301, -0.39104242, -0.90102103,  0.35669534,  2.08791061,
        0.38292754,  1.72240816,  0.36033848,  0.24585068, -0.52811792,
        0.47907222, -0.08828167, -0.61214436,  1.92059345, -0.05330126,
       -0.38714348, -0.21262032,  1.34366032, -0.5792204 , -0.18203616,
       -0.45318532, -0.54677084,  1.6845122 , -0.22044966, -0.22276744,
       -0.00483172, -1.82923445, -0.56330093, -0.1563281 , -0.08520892,
       -1.3009565 ,  0.29299475, -0.95974259, -0.58459672, -0.84464118,
        0.45772928,  0.48273986,  0.31709813, -1.46979537,  0.09205277,
        0.93467494,  0.33039886, -0.0353428 , -0.50726393,  0.35

In [ ]:
np.max(arr), np.min(arr), np.mean(arr), np.var(arr), np.std(arr)

(2.0879106116404205,
 -2.51107142127809,
 -0.01515222665180942,
 0.7330764706668839,
 0.8561988499565296)

In [ ]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [ ]:
np.logspace(2,4,3)

array([  100.,  1000., 10000.])

In [ ]:
time_00 = 1600
time_19 = 8350
np.linspace(time_00, time_19, 10)

array([1600., 2350., 3100., 3850., 4600., 5350., 6100., 6850., 7600.,
       8350.])

In [ ]:
np.random.seed(1)
res1 = np.random.randint(10, 100, 10)

np.random.seed(2)
res2 = np.random.randint(10, 100, 10)

np.random.seed(1)
res3 = np.random.randint(10, 100, 10)

res1, res2, res3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]))

In [ ]:
np.random.rand(10)


array([0.18626021, 0.34556073, 0.39676747, 0.53881673, 0.41919451,
       0.6852195 , 0.20445225, 0.87811744, 0.02738759, 0.67046751])

In [ ]:
np.random.randn(10)

array([ 1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521])

In [ ]:
x = np.random.randint(1, 10, (4, 4))
x

array([[5, 9, 2, 5],
       [1, 4, 3, 1],
       [5, 3, 8, 8],
       [9, 7, 4, 8]])

In [ ]:
np.random.shuffle(x)
x

array([[9, 7, 4, 8],
       [5, 9, 2, 5],
       [1, 4, 3, 1],
       [5, 3, 8, 8]])

In [ ]:
arr = np.random.randint(0,10,(3,3))
arr

array([[2, 5, 7],
       [8, 4, 4],
       [7, 7, 4]])

In [ ]:
 #np.any(arr > 5)

 #np.all(arr > 5)

# np.all(arr < 10)

# np.argmin(arr, 0)

# np.argmax(arr, 1)

# np.argsort(arr, axis=0)

# arr[np.where(arr>5)]
np.where(arr<5, 10, arr)

array([[10,  5,  7],
       [ 8, 10, 10],
       [ 7,  7, 10]])

In [ ]:
arr = np.random.randint(0,10,(4,4))
arr

array([[9, 0, 2, 0],
       [7, 1, 7, 9],
       [8, 4, 0, 1],
       [9, 8, 2, 3]])

In [ ]:
# np.max(arr, 1)

# np.mean(arr, 0)

# np.min(arr, 1)

# np.std(arr), np.std(arr, 0)

np.sum(arr)

70

In [ ]:
arr = np.random.randint(0,10,(2,4))
arr

array([[1, 2, 7, 2],
       [6, 0, 9, 2]])

In [ ]:
arr1 = arr[..., np.newaxis]
#arr1.shape

#arr2 = np.squeeze(arr1, axis=-1)
#arr2.shape

#arr3 = np.transpose(arr1, (2,1,0))
#arr1.shape , arr3.shape
#arr4 = arr1.reshape(4,2,1) 
#arr4.shape

arr5 = arr2.T
arr.shape, arr5.shape

((2, 4), (4, 2))