In [ ]:
import numpy as np


In [ ]:
arr = np.array([1,2,3], dtype = 'int32')
type(arr), arr

(numpy.ndarray, array([1, 2, 3], dtype=int32))

In [ ]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print(arr2.size)
print(arr2.dtype)


[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [ ]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [ ]:
a=np.random.randint(2,10,size=(5,))
b=np.random.randint(2,10,size=(2,4))
c=np.random.randint(2,10,size=(2,3,4))
print(a)
print(b)
print(c)

[7 5 7 2 3]
[[7 8 8 5]
 [9 2 3 8]]
[[[3 7 9 6]
  [8 5 5 5]
  [2 6 8 9]]

 [[4 4 3 3]
  [8 4 4 8]
  [3 2 4 7]]]


In [ ]:
arr2.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2[1]


array([4, 5, 6])

In [ ]:
arr2[1,1]

5

In [ ]:
ls = [1,2,3]
ls[1] = 5
ls

[1, 5, 3]

In [ ]:
arr3 = np.array([[1,2,3],[0,1,0]])

arr3[1][1] = 0
arr3

array([[1, 2, 3],
       [0, 0, 0]])

In [ ]:
arr3[0] = 5
arr3[1]= [5,6,7]
arr3

array([[5, 5, 5],
       [5, 6, 7]])

In [ ]:
idx = arr3>5
idx

array([[False, False, False],
       [False,  True,  True]])

In [ ]:
arr3[idx]

array([6, 7])

In [ ]:
arr3[idx] = 100
arr3

array([[  5,   5,   5],
       [  5, 100, 100]])

In [ ]:
zero_arr = np.zeros(shape = (2,3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
type(zero_arr)


numpy.ndarray

In [ ]:
zero_arr.dtype

dtype('float64')

In [ ]:
z2 = zero_arr.astype('int64')
z2.dtype

dtype('int64')

In [ ]:
one_arr = np.ones((2,3))
one_arr.dtype, one_arr

(dtype('float64'), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [ ]:
one_arr2 = np.ones((2,3,2)).astype('int')
one_arr2.dtype, one_arr2

(dtype('int64'), array([[[1, 1],
         [1, 1],
         [1, 1]],
 
        [[1, 1],
         [1, 1],
         [1, 1]]]))

In [ ]:
id = np.identity(n=5, dtype = np.int8)
id

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [ ]:
arr= np.arange(1,11)

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
A = [[1,2,3],[4,5,6]]
B = [[4,5,6],[1,2,3]]
A+B

[[1, 2, 3], [4, 5, 6], [4, 5, 6], [1, 2, 3]]

In [ ]:
a = np.array(A)
b = np.array(B)
a+b

array([[5, 7, 9],
       [5, 7, 9]])