<a href="https://colab.research.google.com/github/uichann/My_Repository/blob/main/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = np.random.randint(0,10,(2,4))
b = np.random.randint(0,10,(2,4))

In [2]:
np.dot(a,b.T)

array([[ 31,  44],
       [ 95, 124]])

In [3]:
np.inner(a,b)

array([[ 31,  44],
       [ 95, 124]])

In [4]:
#np.inner(a,b.T) # 에러

ValueError: ignored

In [5]:
a = np.array([[1,-1], [1,1]])

In [6]:
value, vector = np.linalg.eig(a)
value, vector

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [7]:
arr = np.random.randn(3,3)
arr

array([[ 0.45259498,  1.3685253 ,  0.91127219],
       [-0.79108072,  1.08932706,  0.95330517],
       [-0.93062985, -0.31585403, -0.04524871]])

In [8]:
mat = np.dot(arr.T, arr)
mat, np.linalg.inv(mat)

(array([[ 1.69672284,  0.05158524, -0.29959431],
        [ 0.05158524,  3.15925872,  2.29985216],
        [-0.29959431,  2.29985216,  1.74125519]]),
 array([[  37691.3052388 , -138630.07537598,  189587.82128973],
        [-138630.07537598,  509894.99064698, -697322.18477883],
        [ 189587.82128973, -697322.18477883,  953644.45682176]]))

In [9]:
np.dot(mat, np.linalg.inv(mat))

array([[ 1.00000000e+00, -2.62481366e-12,  2.27940322e-11],
       [-1.56302791e-12,  1.00000000e+00,  3.93696521e-10],
       [-2.84123147e-11,  2.49578325e-10,  1.00000000e+00]])